accounts/urls.py
from django.urls import path
from accounts.views import UserRegistrationView, UserLoginView, UserLogoutView, UserProfileUpdateView, ChangePasswordView

urlpatterns = [
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('profile/', UserProfileUpdateView.as_view(), name='profile'),
    path('change_password/', ChangePasswordView.as_view(), name='change_password'),
]

pai_bank/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('accounts/', include('accounts.urls')),
    path('transactions/', include('transactions.urls')),
]

transactions/urls.py
from django.urls import path
from transactions.views import DepositMoneyView, TransactionReportView, WithdrawMoneyView, LoanRequestView, LoanListView, PayLoanView, TransferMoneyView

urlpatterns = [
    path('deposit/', DepositMoneyView.as_view(), name='deposit_money'),
    path('report/', TransactionReportView.as_view(), name='transaction_report'),
    path('withdraw/', WithdrawMoneyView.as_view(), name='withdraw_money'),
    path('transfer/', TransferMoneyView.as_view(), name='transfer_money'),
    path('loan_request/', LoanRequestView.as_view(), name='loan_request'),
    path('loans/', LoanListView.as_view(), name='loan_list'),
    path('loans/<int:loan_id>/', PayLoanView.as_view(), name='pay'),
]

transactions/models.py
from django.db import models
from accounts.models import UserBankAccount
from transactions.constants import TRANSACTION_TYPE
# Create your models here.

class Transaction(models.Model):
    account = models.ForeignKey(UserBankAccount, related_name='transactions', on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=12, decimal_places=2)
    balance_after_transaction = models.DecimalField(max_digits=12, decimal_places=2)
    transaction_type = models.IntegerField(choices=TRANSACTION_TYPE, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    loan_approve = models.BooleanField(default=False)
    to_account = models.IntegerField(default=1)

    class Meta:
        ordering = ['timestamp']


class Bank(models.Model):
    name = models.CharField(max_length=100, default='bankrupt', null=True, blank=True)
    is_bankrupt = models.BooleanField(default=False)

    def __str__(self):
        return f"bankrupt is {self.is_bankrupt}"    

transactions/forms.py
from django import forms
from transactions.models import Transaction, Bank

class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ['amount', 'transaction_type']

    def __init__(self, *args, **kwargs):
        self.account = kwargs.pop('account')
        super().__init__(*args, **kwargs)

        self.fields['transaction_type'].disabled = True
        self.fields['transaction_type'].widget = forms.HiddenInput()

    def save(self, commit=True):
        self.instance.account = self.account
        self.instance.balance_after_transaction = self.account.balance
        return super().save()


class DepositForm(TransactionForm):
    def clean_amount(self):
        min_deposit_amount = 100
        amount = self.cleaned_data.get('amount')
        if amount < min_deposit_amount:
            raise forms.ValidationError(
                f"You need to deposit at least {min_deposit_amount} $"
            )
        return amount
    

class WithdrawForm(TransactionForm):
    def clean_amount(self):

        bank, created = Bank.objects.get_or_create()
        # print(Bank.objects.get().is_bankrupt)

        if bank.is_bankrupt:
            raise forms.ValidationError(
                "The bank was bankrupted, no withdraw allow!"
            )
        
        account = self.account
        min_withdraw_amount = 500
        max_withdraw_amount = 20000
        balance = account.balance
        amount = self.cleaned_data.get('amount')
        if amount < min_withdraw_amount:
            raise forms.ValidationError(
                f"You can withdraw at least {min_withdraw_amount} $"
            )
        if amount > max_withdraw_amount:
            raise forms.ValidationError(
                f"You can withdraw at most {max_withdraw_amount} $"
            )
        if amount > balance:
            raise forms.ValidationError(
                f"You have {balance} $ in your account. You can not withdraw more than your account balance."
            )
        return amount
    


class LoanRequestForm(TransactionForm):
    def clean_amount(self):
        amount = self.cleaned_data.get('amount')
        return amount


class TransferForm(TransactionForm):
    class Meta:
        model = Transaction
        fields = ['amount', 'transaction_type', 'to_account']

    def clean_amount(self):
        if Bank.objects.first().is_bankrupt:
            raise forms.ValidationError(
                "The bank was bankrupted, no withdraw allow!"
            )
        
        amount = self.cleaned_data.get('amount')

        if amount > self.account.balance:
            raise forms.ValidationError(
                f"You have {self.account.balance} $ in your account. You can't transfer more than your account balance"
            )
        
        return amount

transactions/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.views.generic import CreateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from transactions.models import Transaction
from django.urls import reverse_lazy
from transactions.forms import DepositForm, WithdrawForm, LoanRequestForm, TransferForm
from transactions.constants import DEPOSIT, WITHDRAW, LOAN, LOAN_PAID, TRANSFER
from django.contrib import messages
from datetime import datetime
from django.db.models import Sum
from django.views import View
from accounts.models import UserBankAccount
from django.core.mail import EmailMessage, EmailMultiAlternatives
from django.template.loader import render_to_string
# Create your views here.

def send_transaction_email(user, amount, subject, template):
    message = render_to_string(template, {
        'user' : user,
        'amount' : amount,
    })
    send_email = EmailMultiAlternatives(subject, '', to=[user.email])
    send_email.attach_alternative(message, "text/html")
    send_email.send()


class TransactionCreateMixin(LoginRequiredMixin, CreateView):
    template_name = 'transactions/transaction_form.html'
    model = Transaction
    title = ''
    success_url = reverse_lazy('transaction_report')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({
            'account' : self.request.user.account
        })
        return kwargs
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'title' : self.title
        })
        return context



class DepositMoneyView(TransactionCreateMixin):
    form_class = DepositForm
    title = 'Deposit'

    def get_initial(self):
        initial = {'transaction_type' : DEPOSIT}
        return initial
    
    def form_valid(self, form):
        amount = form.cleaned_data.get('amount')
        account = self.request.user.account
        account.balance += amount
        account.save(
            update_fields = ['balance']
        )

        messages.success(
            self.request, f'{"{:,.2f}".format(float(amount))}$ was deposited to your account successfully'
        )

        # mail_subject = 'Deposit Message'
        # message = render_to_string('transactions/deposit_email.html', {
        #     'user' : self.request.user,
        #     'amount' : amount,
        # })
        # to_email = self.request.user.email
        # send_email = EmailMultiAlternatives(mail_subject, '', to=[to_email])
        # send_email.attach_alternative(message, "text/html")
        # send_email.send()

        send_transaction_email(self.request.user, amount, "Deposit Message", "transactions/deposit_email.html")

        return super().form_valid(form)


class WithdrawMoneyView(TransactionCreateMixin):
    form_class = WithdrawForm
    title = 'Withdraw Money'

    def get_initial(self):
        initial = {"transaction_type" : WITHDRAW}
        return initial
    
    def form_valid(self, form):
        amount = form.cleaned_data.get('amount')
        self.request.user.account.balance -= form.cleaned_data.get('amount')

        self.request.user.account.save(update_fields = ['balance'])

        messages.success(
            self.request, f'Successfully withdrawn {"{:,.2f}".format(float(amount))}$ from your account'
        )

        send_transaction_email(self.request.user, amount, "Withdraw Message", "transactions/withdraw_email.html")

        return super().form_valid(form)
    


class LoanRequestView(TransactionCreateMixin):
    form_class = LoanRequestForm
    title = 'Request For Loan'

    def get_initial(self):
        initial = {'transaction_type' : LOAN}
        return initial
    
    def form_valid(self, form):
        amount = form.cleaned_data.get('amount')

        current_loan_count = Transaction.objects.filter(account = self.request.user.account, transaction_type = 3, loan_approve = True).count()

        if current_loan_count >= 3:
            return HttpResponse("You have cross the loan limits")

        messages.warning(
            self.request, f'Loan request for {"{:,.2f}".format(float(amount))}$ submitted successfully'
        )

        send_transaction_email(self.request.user, amount, "Loan Request Message", "transactions/loan_email.html")

        return super().form_valid(form)
    

class TransactionReportView(LoginRequiredMixin, ListView):
    template_name = 'transactions/transaction_report.html'
    model = Transaction
    balance = 0
    context_object_name = 'transactions'

    def get_queryset(self):
        queryset = super().get_queryset().filter(
            account = self.request.user.account
        )

        start_date_str = self.request.GET.get('start_date')
        end_date_str = self.request.GET.get('end_date')

        if start_date_str and end_date_str:
            start_date = datetime.strptime(start_date_str, '%Y-%m-%d').date()
            end_date = datetime.strptime(end_date_str, '%Y-%m-%d').date()

            queryset = queryset.filter(timestamp__date__gte=start_date, timestamp__date__lte=end_date)

            self.balance = Transaction.objects.filter(
                timestamp__date__gte=start_date, timestamp__date__lte=end_date
            ).aggregate(Sum('amount'))['amount__sum']

        else:
            self.balance = self.request.user.account.balance

        return queryset.distinct()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'account' : self.request.user.account
        })
        return context
    


class LoanListView(LoginRequiredMixin, ListView):
    model = Transaction
    template_name = 'transactions/loan_request.html'
    context_object_name = 'loans'

    def get_queryset(self):
        user_account = self.request.user.account
        queryset = Transaction.objects.filter(account=user_account, transaction_type=LOAN)
        print(queryset)
        return queryset
    


class PayLoanView(LoginRequiredMixin, View):

    def get(self, request, loan_id):
        loan = get_object_or_404(Transaction, id=loan_id)
        print(loan)
        if loan.loan_approve:
            user_account = loan.account
            if loan.amount < user_account.balance:
                user_account.balance -= loan.amount
                loan.balance_after_transaction = user_account.balance
                user_account.save()
                loan.loan_approve = True
                loan.transaction_type = LOAN_PAID
                loan.save()

                messages.success(
                    self.request, f'Loan paid successfully'
                )
                
                return redirect('transaction_report')
           
            else:
                messages.error(
                    self.request, f"Loan amount is greater than available balance"
                )
        return redirect('loan_list')
    

class TransferMoneyView(TransactionCreateMixin):
    form_class = TransferForm
    title = 'Money Transfer'

    def get_initial(self):
        initial = {'transaction_type' : TRANSFER}
        return initial
    
    def form_valid(self, form):
        amount = form.cleaned_data.get('amount')
        to_account_number = form.cleaned_data.get('to_account')

        try:
            to_account = UserBankAccount.objects.get(account_no=to_account_number)

        except UserBankAccount.DoesNotExist:
            form.add_error('to_account', 'The account does not exist.')
            
            return self.form_invalid(form)
        
        account = self.request.user.account
        account.balance -= amount
        to_account.balance += amount

        account.save(
            update_fields = ['balance']
        )

        to_account.save(
            update_fields = ['balance']
        )

        messages.success(
            self.request, f'{"{:,.2f}".format(float(amount))}$ was transferred from your account successfully.'
        )

        send_transaction_email(self.request.user, amount, "Money Transfer Message", "transactions/transfer_email.html")

        send_transaction_email(to_account.user, amount, "Money Receiver Message", "transactions/receiver_email.html")
        
        return super().form_valid(form)

transactions/templates/transactions/admin_email.html
{% extends "core/core_message.html" %}
{% block content %}


<div class="border rounded-lg text-left shadow-xl sm:my-8 sm:w-full sm:max-w-lg">
    <div class="bg-white px-4 pb-4 pt-5 sm:p-6 sm:pb-4">
        
        <div class="mt-3 text-center sm:mt-0 sm:text-left">
            <h3 class="text-base font-semibold text-gray-900">Hello, {{user.username}}</h3>
            <div class="mt-2">
                <h4 class="text-base font-normal text-gray-900" id="modal-title">Congratulations!! Your Loan Request has been approved.</h4>
                <p class="text-sm text-gray-500">After ${{amount}} loan approval your total amount is ${{user.account.balance}}</p>
            </div>
        </div>
        
    </div>

    <div class="bg-indigo-100 px-4 py-3 sm:px-6">
        <h4 class="text-base font-normal text-gray-900">Thanks for banking with us</h4>
        <h5 class="mt-2 text-base font-semibold text-gray-900">Pai Bank</h5>
    </div>

</div>

{% endblock content %}

transactions/templates/transactions/deposit_email.html
{% extends "core/core_message.html" %}
{% block content %}


<div class="border rounded-lg text-left shadow-xl sm:my-8 sm:w-full sm:max-w-lg">
    <div class="bg-white px-4 pb-4 pt-5 sm:p-6 sm:pb-4">
        
        <div class="mt-3 text-center sm:mt-0 sm:text-left">
            <h3 class="text-base font-semibold text-gray-900">Hello, {{user.username}}</h3>
            <div class="mt-2">
                <p class="text-sm text-gray-500">Your Deposite request for ${{amount}} has been successfully completed. After deposite your total amount is ${{user.account.balance}}</p>
            </div>
        </div>
        
    </div>

    <div class="bg-indigo-100 px-4 py-3 sm:px-6">
        <h4 class="text-base font-normal text-gray-900">Thanks for banking with us</h4>
        <h5 class="mt-2 text-base font-semibold text-gray-900">Pai Bank</h5>
    </div>

</div>

{% endblock content %}

transactions/templates/transactions/loan_email.html
{% extends "core/core_message.html" %}
{% block content %}


<div class="border rounded-lg text-left shadow-xl sm:my-8 sm:w-full sm:max-w-lg">
    <div class="bg-white px-4 pb-4 pt-5 sm:p-6 sm:pb-4">
        
        <div class="mt-3 text-center sm:mt-0 sm:text-left">
            <h3 class="text-base font-semibold text-gray-900">Hello, {{user.username}}</h3>
            <div class="mt-2">
                <p class="text-sm text-gray-500">Your Loan request for ${{amount}} has been successfully sent to admin. Wait for admin approval. After getting admin approval you will get the loan and also get a confirmation mail.</p>
            </div>
        </div>
        
    </div>

    <div class="bg-indigo-100 px-4 py-3 sm:px-6">
        <h4 class="text-base font-normal text-gray-900">Thanks for banking with us</h4>
        <h5 class="mt-2 text-base font-semibold text-gray-900">Pai Bank</h5>
    </div>

</div>

{% endblock content %}

transactions/templates/transactions/loan_request.html
{% extends "core/base.html" %}
{% load humanize %}
{% block title %} Loan Report {% endblock title %}
{% block content %}


<section class="min-h-screen my-10 mx-2 sm:mx-0">
    <div class="shadow-md mx-auto max-w-7xl px-2 sm:px-10 pb-10">
        <div class="mx-auto max-w-2xl text-center">
            <h2 class="text-balance text-3xl font-semibold tracking-tight text-gray-900 sm:text-4xl">Loan Report</h2>
        </div>
    
        

        <div class="overflow-x-auto snap-x mt-16">
            <table class="table-fixed border-collapse border border-slate-400 w-full min-w-[1000px]">

                <thead>
                    <tr class="bg-indigo-900 text-white">
                        <th class="border border-slate-300 py-2">Loan ID</th>
                        <th class="border border-slate-300 py-2">Loan Amount</th>
                        <th class="border border-slate-300 py-2">Loan Approved</th>
                        <th class="border border-slate-300 py-2">Action</th>
                    </tr>
                </thead>
    
                <tbody>
                    {% for loan in loans %}
                        <tr class="text-center bg-slate-100 hover:bg-slate-50">
                            <td class="border border-slate-300 py-2.5">{{loan.id}}</td>

                            <td class="border border-slate-300 py-2.5 font-semibold">
                                <span class=" {% if loan.loan_approve %} text-yellow-600 {% else %} text-green-700 {% endif %} ">
                                    $ {{loan.amount|floatformat:2|intcomma}}
                                </span>
                            </td>

                            <td class="border border-slate-300 py-2.5 font-medium">{{loan.loan_approve}}</td>

                            <td class="border border-slate-300 py-2.5 font-semibold">

                                {% if loan.loan_approve %}
                                    <a class="text-yellow-950 hover:text-yellow-900 bg-yellow-400 hover:bg-yellow-200 py-1 rounded-full mx-5 block" href=' {% url "pay" loan.id %} '>Pay</a>
                                {% else %}
                                    <p class=" text-red-700 bg-red-100 py-1 rounded-full mx-5">Loan Pending</p>
                                {% endif %}
                                
                                
                            </td>
    
                        </tr>
                    
                    {% endfor %}
                    
                </tbody>
                  
            </table>
        </div>

    </div>
</section>
  

{% endblock content %}

transactions/templates/transactions/receiver_email.html
{% extends "core/core_message.html" %}
{% block content %}


<div class="border rounded-lg text-left shadow-xl sm:my-8 sm:w-full sm:max-w-lg">
    <div class="bg-white px-4 pb-4 pt-5 sm:p-6 sm:pb-4">
        
        <div class="mt-3 text-center sm:mt-0 sm:text-left">
            <h3 class="text-base font-semibold text-gray-900">Hello, {{user.username}}</h3>
            <div class="mt-2">
                <h4 class="text-base font-normal text-gray-900" id="modal-title">Congratulations!!</h4>
                <p class="text-sm text-gray-500">You have received ${{amount}} successfully. After receiving money your total amount is ${{user.account.balance}}</p>
            </div>
        </div>
        
    </div>

    <div class="bg-indigo-100 px-4 py-3 sm:px-6">
        <h4 class="text-base font-normal text-gray-900">Thanks for banking with us</h4>
        <h5 class="mt-2 text-base font-semibold text-gray-900">Pai Bank</h5>
    </div>

</div>

{% endblock content %}

transactions/templates/transactions/transaction_form.html
{% extends "core/base.html" %}
{% block title %} {{title}} {% endblock title %}
{% block content %}

<div class="h-screen">
    <div class="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8">

        <div class="shadow-lg sm:mx-auto sm:w-full sm:max-w-md p-10 bg-gray-50">
    
            <div class="sm:mx-auto sm:w-full sm:max-w-sm">
    
                {% if title == 'Request For Loan' %}
                    <div class="bg-slate-100 px-4 py-2 border hover:bg-white mb-10">
                        <a href=" {% url "loan_list" %} " class="block text-base/6 font-medium text-gray-900">View All Loan List</a>
                    </div>
                {% endif %}
              
                <h2 class="text-center text-2xl/9 font-bold tracking-tight text-gray-900">{{title}}</h2>
        
            </div>
        
            
          
            <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
        
                <form class="space-y-6" method="POST">
                    {% csrf_token %}

                    {% if title == 'Money Transfer' %}
                        <div>
                            <label for="to_account" class="block text-base/6 font-medium text-gray-900">Account Number</label>
            
                            <div class="mt-2">
                                <input id="to_account" name="to_account" type="number" required placeholder="Account Number" class="block w-full rounded-md border-0 px-3 py-1.5 text-gray-900 font-medium shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm/6">
                            </div>
            
                            {% if form.to_account.errors %}
                                <div class="text-red-600 text-sm">
                                    {% for error in form.to_account.errors %}
                                        <p>{{error}}</p>
                                    {% endfor %}
                                </div>
                            {% endif %}
            
                        </div>
                    {% endif %}
        
                    <div>
                        <label for="amount" class="block text-base/6 font-medium text-gray-900">Amount</label>
        
                        <div class="mt-2">
                            <input id="amount" name="amount" type="number" required placeholder="Amount" class="block w-full rounded-md border-0 px-3 py-1.5 text-gray-900 font-medium shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm/6">
                        </div>
        
                        {% if form.amount.errors %}
                            <div class="text-red-600 text-sm">
                                {% for error in form.amount.errors %}
                                    <p>{{error}}</p>
                                {% endfor %}
                            </div>
                        {% endif %}
        
                    </div>
            
                    
            
                    <div>
                        <button type="submit" class="flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm/6 font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Submit</button>
                    </div>
        
                </form>
          
            </div>
    
        </div>
        
    </div>
</div>
  






{% endblock content %}

transactions/templates/transactions/transaction_report.html
{% extends "core/base.html" %}
{% load humanize %}
{% block title %} Transaction Report {% endblock title %}

{% block content %}


<section class="min-h-screen my-10 mx-2 sm:mx-0">
    <div class="shadow-md mx-auto max-w-7xl px-2 sm:px-10 pb-10">
        <div class="mx-auto max-w-2xl text-center">
            <h2 class="text-balance text-3xl font-semibold tracking-tight text-gray-900 sm:text-4xl">Transaction Report</h2>
        </div>
    
        <form action=" {% url "transaction_report" %} " method="get" class="mt-16 sm:mt-20 mb-10">
            
    
            <div class="grid grid-cols-1 gap-x-8 gap-y-4 sm:grid-cols-1 md:grid-cols-3 lg:grid-cols-3">

                <div class="flex items-center rounded-md bg-white border-0 px-3.5 py-2 text-gray-900 shadow-sm ring-1 ring-gray-300">
                    <label for="start_date" class="block text-sm font-semibold text-gray-900 mr-8">From:</label>

                    <input type="date" name="start_date" id="start_date" class="block w-full appearance-none sm:text-sm outline-none text-gray-900 focus:outline-none active:outline-none">
                </div>

                <div class="flex items-center rounded-md border-0 px-3.5 py-2 text-gray-900 shadow-sm ring-1 ring-gray-300">
                    <label for="end_date" class="block text-sm font-semibold text-gray-900 mr-8">To:</label>

                    <input type="date" name="end_date" id="end_date" class="block w-full appearance-none sm:text-sm outline-none text-gray-900 focus:outline-none active:outline-none">
                </div>
    
                <div>
                    <button type="submit" class="block w-full rounded-md bg-indigo-600 px-3.5 py-2.5 text-center text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Filter</button>
                </div>
            
            </div>
                
        </form>

        <div class="overflow-x-auto snap-x">
            <table class="table-fixed border-collapse border border-slate-400 w-full min-w-[1000px]">

                <thead>
                    <tr class="bg-indigo-900 text-white">
                        <th class="border border-slate-300 py-2">Date</th>
                        <th class="border border-slate-300 py-2">Transaction Type</th>
                        <th class="border border-slate-300 py-2">Amount</th>
                        <th class="border border-slate-300 py-2">Balance After Transaction</th>
                    </tr>
                </thead>
    
                <tbody>
                    {% for transaction in transactions %}
                        <tr class="text-center bg-slate-100 hover:bg-slate-50">
                            <td class="border border-slate-300 py-2.5">{{transaction.timestamp|date:"F d, Y h:i A"}}</td>
                            <td class="border border-slate-300 py-2.5 font-semibold">
                                <span class="px-3 py-1 mx-5 rounded-full block
                                {% if transaction.get_transaction_type_display == 'Withdraw' or transaction.get_transaction_type_display == 'Loan Paid' or transaction.get_transaction_type_display == 'Money Transfer' %} text-red-700 bg-red-100
                                {% elif transaction.get_transaction_type_display == 'Loan' %}
                                    {% if transaction.loan_approve %}
                                        text-green-700 bg-green-100
                                    {% else %}
                                        text-yellow-600 bg-yellow-100
                                    {% endif %} 

                                {% else %} text-green-700 bg-green-100
                                {% endif %}">
                                    {{transaction.get_transaction_type_display}}
                                </span>
                            </td>
    
                            <td class="border border-slate-300 py-2.5 font-medium">
                                <span class=" {% if transaction.get_transaction_type_display == 'Withdraw' or transaction.get_transaction_type_display == 'Loan Paid' or transaction.get_transaction_type_display == 'Money Transfer' %} text-red-700
                                {% elif transaction.get_transaction_type_display == 'Loan' %}
                                    {% if transaction.loan_approve %}
                                        text-green-700
                                    {% else %}
                                        text-yellow-600
                                    {% endif %}
                                {% else %} text-green-700
                                {% endif %} ">
                                    $ {{transaction.amount|floatformat:2|intcomma}}
                                </span>
                            </td>
                            <td class="border border-slate-300 py-2.5 font-medium">$ {{transaction.balance_after_transaction|floatformat:2|intcomma}}</td>
                        </tr>
                    
                    {% endfor %}
                    
                </tbody>
    
                <tfoot>
                    <tr class="bg-indigo-600 text-white text-center">
                        <th class="border border-slate-300 py-3" colspan="3">Current Balance</th>
                        <th class="border border-slate-300 py-3 bg-indigo-950">$ {{account.balance|floatformat:2|intcomma}}</th>
                    </tr>
                </tfoot>

            </table>
        </div>


    </div>
</section>
  




{% endblock content %}

transactions/templates/transactions/transfer_email.html
{% extends "core/core_message.html" %}
{% block content %}


<div class="border rounded-lg text-left shadow-xl sm:my-8 sm:w-full sm:max-w-lg">
    <div class="bg-white px-4 pb-4 pt-5 sm:p-6 sm:pb-4">
        
        <div class="mt-3 text-center sm:mt-0 sm:text-left">
            <h3 class="text-base font-semibold text-gray-900">Hello, {{user.username}}</h3>
            <div class="mt-2">
                <p class="text-sm text-gray-500">Your Money Transfer request for ${{amount}} has been successfully completed. After deposite your total amount is ${{user.account.balance}}</p>
            </div>
        </div>
        
    </div>

    <div class="bg-indigo-100 px-4 py-3 sm:px-6">
        <h4 class="text-base font-normal text-gray-900">Thanks for banking with us</h4>
        <h5 class="mt-2 text-base font-semibold text-gray-900">Pai Bank</h5>
    </div>

</div>

{% endblock content %}

transactions/templates/transactions/withdraw_email.html
{% extends "core/core_message.html" %}
{% block content %}


<div class="border rounded-lg text-left shadow-xl sm:my-8 sm:w-full sm:max-w-lg">
    <div class="bg-white px-4 pb-4 pt-5 sm:p-6 sm:pb-4">
        
        <div class="mt-3 text-center sm:mt-0 sm:text-left">
            <h3 class="text-base font-semibold text-gray-900">Hello, {{user.username}}</h3>
            <div class="mt-2">
                <p class="text-sm text-gray-500">Your Withdrawal request for ${{amount}} has been successfully completed. After deposite your total amount is ${{user.account.balance}}</p>
            </div>
        </div>
        
    </div>

    <div class="bg-indigo-100 px-4 py-3 sm:px-6">
        <h4 class="text-base font-normal text-gray-900">Thanks for banking with us</h4>
        <h5 class="mt-2 text-base font-semibold text-gray-900">Pai Bank</h5>
    </div>

</div>

{% endblock content %}